### ISSUE TITLE
Vibration motor manager

### ISSUE THREAD

**Issue by hadrien-toma** [GDGToulouse/devfest-embedded-devices-monorepo#10]
# Proof Of Concept

## Metadata

| key | value |
| ----| ----- |
| name | vibration-motor-manager |

## Description

Talking about countdowns, one of the goals we want is that we want to not disturb the speakers as much as possible, we want to tell them about the progress of their talk but without creating a disturbance in their presentation.

A [vibration motor](https://www.amazon.fr/dp/B074M24S21/ref=pe_3044141_185740131_TE_item_image) stuck on the table may be a good way to transmit an alert to the speaker without triggering all the attendees and without confusing the speaker so much.

## Tasks

- [ ] Create a bash script for configuring the vibration motor
- [ ] Create a bash script for activating the vibration motor
- [ ] Create a bash script for deactivating the vibration motor
- [ ] Code the controllers scripts of the API outputted from #11

## Inputs

- 1 BeagleBone Black
- 1 BeagleBone Black power supply
- 1 serial USB adapters and its jumpers
- 1 micro-SD cards flashed with the latest custom distribution version
- 1 vibration motor
- 1 semiconductor rectifier
- 1 NPN BC337 
- 1 breadboard and few jumpers

## References

- https://www.circuito.io/app?components=8449,9443,200000

**Comment by hadrien-toma** [comment]
Blocked by #11
