### ISSUE TITLE
Gyrophare manager

### ISSUE THREAD

**Issue by hadrien-toma** [GDGToulouse/devfest-embedded-devices-monorepo#13]
# Proof Of Concept

## Metadata

| key | value |
| ----| ----- |
| name | gyrophare-manager |

## Description

Talking about countdowns, one of the goals we want is that we want to not disturb the speakers as much as possible, we want to tell them about the progress of their talk but without creating a disturbance in their presentation.

An [USB gyrophare](https://www.amazon.fr/dp/B07T5BCPVJ/ref=pe_3044141_189395771_TE_3p_dp_1) oriented only through the speaker may be a good way to transmit an alert to the speaker without triggering all the attendees and without confusing the speaker so much.

## Tasks

- [ ] Create a bash script for configuring the gyrophare
- [ ] Create a bash script for activating the gyrophare
- [ ] Create a bash script for deactivating the gyrophare
- [ ] Code the controllers scripts of the API outputted from #12 

## Inputs

- 1 BeagleBone Black
- 1 BeagleBone Black power supply
- 1 serial USB adapters and its jumpers
- 1 micro-SD cards flashed with the latest custom distribution version
- 1 USB gyrophare

**Comment by hadrien-toma** [comment]
Blocked by #12
