### ISSUE TITLE
I2C MCP23017 manager

### ISSUE THREAD

**Issue by hadrien-toma** [GDGToulouse/devfest-embedded-devices-monorepo#16]
# Proof Of Concept

## Metadata

| key | value |
| ----| ----- |
| name | i2c-mcp23017-manager |

## Description

Talking about countdowns, one of the goals we want is that we want to not disturb the speakers as much as possible, we want to tell them about the progress of their talk but without creating a disturbance in their presentation.

A progress bar made of 16 LEDs oriented only through the speaker may be a good way to transmit the time ellapsed/left for the talk to the speaker without triggering all the attendees and without confusing the speaker so much.

The [MCP23017](http://ww1.microchip.com/downloads/en/devicedoc/20001952c.pdf) 16-bit I/O expander allows to control 16 GPIOs with I2C. This provides a nice economy of PIN consumption on BeagleBone Black side: only the PIN for I2C are used and we gain 16 I/O.

## Tasks

- [ ] Create a bash script for configuring the MCP23017
- [ ] Create a bash script that updates the state of the 16-bits and try it with LEDs
- [ ] Code the controllers scripts of the API outputted from #15 

## Inputs

- 1 BeagleBone Black
- 1 BeagleBone Black power supply
- 1 serial USB adapters and its jumpers
- 1 micro-SD cards flashed with the latest custom distribution version
- 1 MCP23017
- 16 LEDs
- 16 470Ω resistors

## References

- https://github.com/adafruit/Adafruit_CircuitPython_MCP230xx

**Comment by hadrien-toma** [comment]
Blocked by #15
