### ISSUE TITLE
Mono-SN74HC595N manager

### ISSUE THREAD

**Issue by hadrien-toma** [GDGToulouse/devfest-embedded-devices-monorepo#19]
# Proof Of Concept

## Metadata

| key | value |
| ----| ----- |
| name | mono-sn74hc595n-manager |

## Description

Talking about countdowns, one of the goals we want is that we want to not disturb the speakers as much as possible, we want to tell them about the progress of their talk but without creating a disturbance in their presentation.

A progress bar made of 8 LEDs oriented only through the speaker may be a good way to transmit the time ellapsed/left for the talk to the speaker without triggering all the attendees and without confusing the speaker so much.

The [SN74HC595N](https://www.sparkfun.com/products/13699) 8-bit shift register allows to control 8 GPIOs with only few ones. Moreover they can be chained to increase their capabilities. This provides a nice economy of PIN consumption on BeagleBone Black side: only the PIN for controlling the shift register are used and it delivers 8 I/Os.

## Tasks

- [ ] Create a bash script for configuring the SN74HC595N
- [ ] Create a bash script that updates the state of the 8-bits and try it with LEDs
- [ ] Code the controllers scripts of the API outputted from #18 

## Inputs

- 1 BeagleBone Black
- 1 BeagleBone Black power supply
- 1 serial USB adapters and its jumpers
- 1 micro-SD cards flashed with the latest custom distribution version
- 1 SN74HC595N
- 8 LEDs
- 8 470Ω resistors

## References

- https://learn.sparkfun.com/tutorials/shift-registers

**Comment by hadrien-toma** [comment]
Blocked by #18
