### ISSUE TITLE
7-segments display manager

### ISSUE THREAD

**Issue by hadrien-toma** [GDGToulouse/devfest-embedded-devices-monorepo#25]
# Proof Of Concept

## Metadata

| key | value |
| ----| ----- |
| name | 7-segments-display-manager |

## Description

Talking about countdowns, one of the goals we want is that we want to not disturb the speakers as much as possible, we want to tell them about the progress of their talk but without creating a disturbance in their presentation.

4 7-segments displays, oriented only through the speaker may be a good way to transmit the time elapsed/left for the talk to the speaker without triggering all the attendees and without confusing the speaker so much.

The [SparkFun large digit driver](https://www.sparkfun.com/products/13279) allows to control a 7-segments display and can be combined with itself in order to increase the number of 7-segments displays added.

## Tasks

- [ ] Create a bash script for configuring 4 SparkFun large digit drivers
- [ ] Create a bash script that updates the state of the 4 7-segments displays
- [ ] Code the controllers scripts of the API outputted from #24 

## Inputs

- 1 BeagleBone Black
- 1 BeagleBone Black power supply
- 1 serial USB adapters and its jumpers
- 1 micro-SD cards flashed with the latest custom distribution version
- 4 SparkFun large digit drivers
- 4 7-Segment Display - 6.5" (Red)
- 1 SparkFun large digit drivers power supply 12VDC 600mA

## References

- https://learn.sparkfun.com/tutorials/large-digit-driver-hookup-guide

**Comment by hadrien-toma** [comment]
Blocked by #24
