### ISSUE TITLE
OpenMV H7 camera manager

### ISSUE THREAD

**Issue by hadrien-toma** [GDGToulouse/devfest-embedded-devices-monorepo#28]
# Proof Of Concept

## Metadata

| key | value |
| ----| ----- |
| name | openmv-h7-camera-manager |

## Description

- As an event organizer, I want to know the number of attendees in each room in order to have more control of crowd moves. This number should be estimated from observing the crowd.
- As an event organizer I want to animate the event : I want to take pictures, to record videos and to stream videos.

For those tasks, we will take advantage of the [OpenMV H7 camera](https://openmv.io/products/openmv-cam-h7).

## Tasks

- [ ] Create a bash script for configuring the OpenMV H7 camera
- [ ] Create a bash script that takes pictures from the OpenMV H7 camera and saves them in files system
- [ ] Create a bash script that records videos from the OpenMV H7 camera and saves them in files system
- [ ] Create the issue about streaming the video stream to the web application
- [ ] Create the issue about processing the video stream in order to estimate the number of people in the crowd
- [ ] Code the controllers scripts of the API outputted from #27 

## Inputs

- 1 BeagleBone Black
- 1 BeagleBone Black power supply
- 1 serial USB adapters and its jumpers
- 1 micro-SD cards flashed with the latest custom distribution version
- 1 OpenMV H7 camera

## References

- https://www.sparkfun.com/products/15325

**Comment by hadrien-toma** [comment]
Blocked by #27
