### ISSUE TITLE
Embedded Mono-node Kubernetes

### ISSUE THREAD

**Issue by hadrien-toma** [GDGToulouse/devfest-embedded-devices-monorepo#3]
# Proof Of Concept

## Metadata

| key | value |
| ----| ----- |
| name | embedded-mono-node-kubernetes |

## Description

- To compare how a mono-node Kubernetes (Minikube, K3D, K3S, ...) works
- To decide which mono-node Kubernetes will be embedded into the BeagleBone Black for production

## Subtasks

- [ ] Search some state of the art data in order to compare the mono-node Kubernetes existing implementations' options (try to not waste time here, 2h by option should be enough)
- [ ] Then summarize _theorical_ key points in a markdown file and put the relative path to this file as a comment of this issue (key points examples: quantity of information found, known issues, limitations, pros, cons) (do not forget to precisely reference your sources)
- [ ] Try to configure Docker on the BeagleBone Black
- [ ] Try to configure micro-K8S on the BeagleBone Black
- [ ] Try to configure K3S on the BeagleBone Black
- [ ] Then summarize _practical_ key points in a markdown file and put the relative path to this file as a comment of this issue (key points examples: pain points, workarounds, warnings, risks, limitations, pros, cons)

## References

- https://medium.com/@shantanoodesai/run-docker-on-a-raspberry-pi-4-with-yocto-project-551d6b615c0b
- https://krakensystems.co/blog/2019/kubernets-on-arm
- https://github.com/teamserverless/k8s-on-raspbian

**Comment by hadrien-toma** [comment]
May be blocked by #4
